### ISSUE TITLE
Destroy

### ISSUE THREAD

**Issue by beppino** [linchpinio/highcharts-elements#1]
Hello! 
I've a, maybe, simple question about your great elements.
After setting a serie and a lot of parameters on my chart (hc-line in my case) I've to reset all parameters to show other series and parameters.
I think that the right method to call is destroy() on the chart object, but this cast an error: Uncaught TypeError: Cannot read property 'length' of undefined, exporting.js:22.
I've tried with this.$.hcChart._chart.destroy().
Can please help me?
With my compliment for your work
Giuseppe

**Comment by jmcgdz** [comment]
@beppino well with highcharts in general, you can chart the chart series, data, parameters without destroying and thus make smooth transitions.

However, to help answer your specific situation, I would need a jsfiddle or some reduced usecase to replicate the problem.

**Comment by beppino** [comment]
Thanks a lot! I'll follow your suggestion. If I have other problems, I'll prepare an example for you!
Bye!
-g
